### ISSUE TITLE
Fix XPath expressions in CoreTests

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-gmljpx20#10]
See PR #2 and #3

**Comment by lgoltz** [comment]
After refactoring, clean up and minor improvements  of the CoreTests several tests in VerifyCoreTests fails cause of incorrect tests. Working branch: https://github.com/opengeospatial/ets-gmljpx20/tree/fixXPathExpressions-10

I propose to rework and improve all test (not only the XPath expressions). The methopd getNodeValueArray() (with access to static fields) should be removed. It should be possible to used XPath expressions instead.

**Comment by alunacob** [comment]
I've just added this pull request [#14](https://github.com/opengeospatial/ets-gmljpx20/pull/14) trying to rework the above mentioned issue.
