### ISSUE TITLE
Check documentation and update if necessary

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-gmljpx20#26]
Documentation: http://cite.opengeospatial.org/te2/about/gmljpx20/2.0/site/

Especially, it must be checked if documentation exactly describes what is covered by this test suite (e.g. are all tests of Core conformance class covered).
From which specification do the tests come from?

**Comment by dstenger** [comment]
Also, describe what versions are covered by the test suite.

**Comment by ghobona** [comment]
I have reviewed the documentation.

**Comment by luciocola** [comment]
Thanks a lot Gobe..
well done
