### ISSUE TITLE
wrong verification of containsUomByReference

### ISSUE THREAD

**Issue by alunacob** [opengeospatial/ets-gmljpx20#28]
I believe https://github.com/opengeospatial/ets-gmljpx20/blob/d861bf3c930800f318db0ea2be79c2af5c1d4565/src/main/java/org/opengis/cite/gmljpx20/core/CoreTests.java#L440

getNodeValue() always returns null. 

Should getTextContent() be used?

**Comment by dstenger** [comment]
Thank you for reporting.
@keshav-nangare Can you please check the reported issue?

**Comment by keshavnangare** [comment]
Added fix with this commit: 559ceb6f24cf821e9f80117da5a156ce484eb5f2
