### ISSUE TITLE
Allow indication that the GMLJP2CoverageCollection is a Collection

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ets-gmljpx20#33]
The code in [Line 399](https://github.com/opengeospatial/ets-gmljpx20/blob/master/src/main/java/org/opengis/cite/gmljpx20/core/CoreTests.java#L399) of org.opengis.cite.gmljpx20.core.CoreTests violates [Requirement 11](http://docs.opengeospatial.org/is/08-085r5/08-085r5.html#requirement_11) in GMLJP2 v2.0.1 (OGC 08-085r5). The text of the requirement is shown below, including the XML fragment from provided by the standard.

![Screenshot 2020-02-21 at 16 43 36](https://user-images.githubusercontent.com/18121038/75053517-5a65c480-54c9-11ea-8cf8-b9b50eca758d.png)

I suggest changing the code to the following.

```java
			for (int i = 0; i < dataRecordElems.getLength(); i++) {
				DeferredElementNSImpl dataRecordElem = (DeferredElementNSImpl) dataRecordElems.item(i);
				
				NodeList fieldElementNL = dataRecordElem.getElementsByTagNameNS("http://www.opengis.net/swe/2.0", "field");
				
				for(int f = 0; f < fieldElementNL.getLength(); f++)
				{
					DeferredElementNSImpl fieldElement = (DeferredElementNSImpl) fieldElementNL.item(f);
					String field = fieldElement.hasAttribute("name") ? fieldElement.getAttribute("name") : null;
					
					boolean hasUom = (fieldElement.getElementsByTagNameNS("http://www.opengis.net/swe/2.0", "uom").getLength()>0);
					
					if (!field.equals("Collection")) {

						if (!hasUom) {
							System.out.println("FAILED!!");
							throw new AssertionError(ErrorMessage.get(GMLJP2_GMLCOV_DATARECORDS_SWEUOM));
						}
					}
				}		
		

			}

```

**Comment by keshavnangare** [comment]
Added fix in PR #31
