### ISSUE TITLE
Merge branch satcen-branch

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-gmljpx20#4]
https://github.com/opengeospatial/ets-gmljpx20/tree/satcen-branch

**Comment by rjmartell** [comment]
The content of this branch is not derived directly from the master branch--it appears to be an Eclipse project, with compiler output included. I assume the test suite in `ets-gmljpx20-master` is intended to update the main branch.

The following (9) files in the `ets-gmljpx20-master` directory appear to differ from what exists in the master branch:

- pom.xml
- src\main\config\test-run-props.xml
- src\main\java\org\opengis\cite\gmljpx20\core\CoreTests.java
- src\main\java\org\opengis\cite\gmljpx20\ErrorMessageKeys.java
- src\main\java\org\opengis\cite\gmljpx20\util\jp2\BitConverter.java
- src\main\java\org\opengis\cite\gmljpx20\util\jp2\Box.java
- src\main\java\org\opengis\cite\gmljpx20\util\jp2\ContigousCodestream.java
- src\main\java\org\opengis\cite\gmljpx20\util\jp2\StreamUtil.java
- src\main\resources\test-run-props.xml

**Comment by rjmartell** [comment]
Created a new branch with these changes. See PR #5.
