### ISSUE TITLE
Confirm whether latest Beta fully supports OGC 08-085r5 (v2.0.1) and OGC 08-085r8 (v2.1)

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ets-gmljpx20#40]
Currently the documentation indicates that the test suite supports OGC 08-085r4 (v2.0). There's a need to check whether the Corrigendum (v2.0.1) is also supported.

There is also a need to confirm that the changes to support  OGC 08-085r8 (v2.1) have been activated.

**Comment by EmDevys** [comment]
2.0.1 version corrects examples that were erroneous, and includes minor editorial changes. No technical change on requirements nor ATS, therefore it should be ok.
It seems better to document a clean version in the ETS, than a version with examples that are incorrect.

Emmanuel

De : ghobona [mailto:notifications@github.com]
Envoyé : lundi 2 novembre 2020 08:49
À : opengeospatial/ets-gmljpx20
Cc : Subscribed
Objet : [opengeospatial/ets-gmljpx20] Confirm whether latest Beta fully supports OGC 08-085r5 (v2.0.1) and OGC 08-085r8 (v2.1) (#40)


Currently the documentation indicates that the test suite supports OGC 08-085r4 (v2.0). There's a need to check whether the Corrigendum (v2.0.1) is also supported.

There is also a need to confirm that the changes to support OGC 08-085r8 (v2.1) have been activated.

**Comment by EmDevys** [comment]
The normative requirements in OGC 08-085r5 (v2.0.1) are the same as in OGC 08-085r4 (if I remember it correctly, only editorial clarifications have been made, and correction of erroneous examples). The xsd schema is unchanged between revision 4 and 5.
For OGC 08-085r8, there is a need to have an ETS for GMLCOV-RGRID (referenceable extension to GMLCOV/CIS 1.0), and an SML 2.0 ETS (for sensor model schemas).

**Comment by ghobona** [comment]
Confirmed that v2.0.1 and v2.1 are supported.
