### ISSUE TITLE
Missing error messages in MessageBundle.properties

### ISSUE THREAD

**Issue by rjmartell** [opengeospatial/ets-gmljpx20#6]
For every error message key declared in `org.opengis.cite.gmljpx20.ErrorMessageKeys` (55 in total) there must be a matching entry in the properties files in the src/main/resources/org/opengis/cite/gmljpx20/ directory:

- MessageBundle.properties
- MessageBundle_en.properties

These properties files currently have only 15 entries.

**Comment by luciocola** [comment]
Ok I will provide

**Comment by luciocola** [comment]
Fixed i am now uploading the changes

**Comment by lgoltz** [comment]
As far as I see the missing error messages are part of PR #2 (at least for MessageBundle.properties but not for MessageBundle_en.properties). 

The key for `GMLJP2_GMLCOV_PRECEDENCE_RANGE_TYPE` in ErrorMessagesKey must be fixed, too (see https://github.com/opengeospatial/ets-gmljpx20/pull/2/files#diff-e56bb2755ddf50527e39216d899e3a75) 

@luciocola Where did you provide your changes?
